import Head from 'next/head'
import styles from './layout.module.css'
import React from 'react'

const name = 'Daniel Boyer'
export const siteTitle = 'Next.js Sample Website'

export default function Layout({ children }:{
    children : React.ReactNode,
}) {
  return (
    <div className={styles.container}>
      <Head>
       <title>Stardle - guess famous stars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>

    </div>
  )
}