import Head from 'next/head'
import styles from './layout.module.css'
import React from 'react'
import Image from 'next/image'
const name = 'Daniel Boyer'
export const siteTitle = 'Next.js Sample Website'

export default function Layout({ children }:{
    children : React.ReactNode,
}) {
  return (
    <div className={styles.container}>
      <Head>
       <title>Stardle - guess famous stars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.topnav}>
          <a className={styles.title} href='https://stardle.app'>STARDLE</a>
          <a className={styles.right}>
            <Image src="/images/question.png" width="24" height="24"/>
          </a>
          <a className={styles.right}>
            <Image src="/images/star.png" width="24" height="24"/>
          </a>
          
        </div>
        {children}
        </main>

    </div>
  )
}