
import Head from 'next/head'
import styles from './layout.module.css'
import React from 'react'
import {useState} from 'react'
import Image from 'next/image'
import Link from 'next/link'
import Statistics from '../pages/statistics'
export const siteTitle = 'Next.js Sample Website'
import Modal from 'react-modal'



Modal.setAppElement("#__next")
export default function Layout({ children }:{
    children : React.ReactNode,
}) {
  const [modalOpen, setModalOpen] = useState(false);
   // Toggle for Modal
   const toggle = () => setModalOpen(!modalOpen);
  return (
    
    <div className={styles.container}>

      <Head>
       <title>Stardle - guess famous stars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal
        isOpen={modalOpen}
        contentLabel="Post modal"
        onRequestClose={()=>toggle()}
        className={styles.Modal}
        overlayClassName={styles.Overlay}
      >
        <Statistics />
      </Modal>

      <main>
        <div className={styles.topnav}>
          <a className={styles.title} href='https://stardle.app'>STARDLE</a>
          <a className={styles.right}>
            <Image src="/images/question.png" width="24" height="24"/>
          </a>
          <a className={styles.right}>
            <Image src="/images/star.png" width="24" height="24"/>
          </a>
          <div className={styles.right}>
       
          <Image onClick={()=>{setModalOpen(true)}} src="/images/stat.png" width="24" height="24"/>
          
          </div>
        </div>
     
        {children}
        </main>
        
   
        <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            99 Cent Arizona Watermelon Flavor
          </span>
        </a>
      </footer>
    </div>
  )
}